// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlpKM8k8d34o_N7IPDkvG-GfshjszLyls',
    appId: '1:130462502963:web:8d40ea7fea95e0e3679346',
    messagingSenderId: '130462502963',
    projectId: 'iottecsup2021ao',
    authDomain: 'iottecsup2021ao.firebaseapp.com',
    databaseURL: 'https://iottecsup2021ao-default-rtdb.firebaseio.com',
    storageBucket: 'iottecsup2021ao.appspot.com',
    measurementId: 'G-MLY646JMMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv42_ADjGfAAKgful0NZDMUgjoeMWI8_c',
    appId: '1:130462502963:android:c8fcbac5280099fd679346',
    messagingSenderId: '130462502963',
    projectId: 'iottecsup2021ao',
    databaseURL: 'https://iottecsup2021ao-default-rtdb.firebaseio.com',
    storageBucket: 'iottecsup2021ao.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmezIRal4ziIKVU4N_lsg9Jx7TM1cDW0M',
    appId: '1:130462502963:ios:a189d4a52d112d25679346',
    messagingSenderId: '130462502963',
    projectId: 'iottecsup2021ao',
    databaseURL: 'https://iottecsup2021ao-default-rtdb.firebaseio.com',
    storageBucket: 'iottecsup2021ao.appspot.com',
    androidClientId: '130462502963-3ihiqlud7fvqgnnpgal96fbbqfgnv4hk.apps.googleusercontent.com',
    iosClientId: '130462502963-o1mgnqu4uraergpos3hlesa7eprn77oa.apps.googleusercontent.com',
    iosBundleId: 'com.example.alertduckapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmezIRal4ziIKVU4N_lsg9Jx7TM1cDW0M',
    appId: '1:130462502963:ios:a189d4a52d112d25679346',
    messagingSenderId: '130462502963',
    projectId: 'iottecsup2021ao',
    databaseURL: 'https://iottecsup2021ao-default-rtdb.firebaseio.com',
    storageBucket: 'iottecsup2021ao.appspot.com',
    androidClientId: '130462502963-3ihiqlud7fvqgnnpgal96fbbqfgnv4hk.apps.googleusercontent.com',
    iosClientId: '130462502963-o1mgnqu4uraergpos3hlesa7eprn77oa.apps.googleusercontent.com',
    iosBundleId: 'com.example.alertduckapp',
  );
}
